# These are supported funding model platforms

github: coinvest518

buy_me_a_coffee: coinvest

custom:
  - https://whop.com/futuristicwealth/
  - https://fwda.site
  - https://cal.com/bookme-daniel/ai-consultation-smb
  - https://linktr.ee/omniai
